(function(){let i=[],m=0,d=!1,r=!1,g=null,l=null,a=null,c=null,p=null;function E(){return[{id:15,title:"🆕 تحديث محتوى",message:"الخوت، راه تزادت تيما جديدة فـ Schreiben B2",time:"11 ماي 2026",unread:!0},{id:14,title:"🆕 تحديث محتوى",message:"الخوت، راه تزادت تيما جديدة فـ Schreiben B2",time:"10 ماي 2026",unread:!0},{id:13,title:"📖 تحديث Lesen Teil 3",message:"الخوت، راه درنا واحد التعديل فالموضوع",time:"10 ماي 2026",unread:!0},{id:12,title:"✍️ تحديث Schreiben",message:"الخوت راه تزادت تيما جديدة",time:"9 ماي 2026",unread:!0},{id:11,title:"📝 تحديث Sprachbausteine Teil 2",message:"الخوت راه تزادت موضوع جديد",time:"8 ماي 2026",unread:!0},{id:10,title:"📚 المواضيع اللي تحطات",message:"السلام الخوت، هادي خلاصة ديال ڭاع المواضيع",time:"7 ماي 2026",unread:!0}]}async function S(){try{const e=await fetch("data/notifications.json");e.ok?i=(await e.json()).notifications||[]:i=E()}catch{console.warn("❌ فشل تحميل notifications.json، استخدام البيانات الافتراضية"),i=E()}i.sort((e,n)=>n.id-e.id),b(),u(),s(),f()}function v(){const e=i.filter(n=>!n.unread).map(n=>n.id);localStorage.setItem("zertiva_notifications_read",JSON.stringify(e))}function b(){const e=localStorage.getItem("zertiva_notifications_read");if(e)try{const n=JSON.parse(e);i.forEach(t=>{t.unread=!n.includes(t.id)})}catch{}}function u(){m=i.filter(e=>e.unread===!0).length}function f(){l&&(m>0?(l.textContent=m>9?"9+":m,l.style.display="flex"):l.style.display="none")}function w(e){const n=document.createElement("div");return n.textContent=e,n.innerHTML}function I(e){return e.includes("🆕")?"🆕":e.includes("📖")?"📖":e.includes("✍️")?"✍️":e.includes("📝")?"📝":e.includes("📚")?"📚":e.includes("🐟")?"🐟":e.includes("🐱")?"🐱":e.includes("⚠️")?"⚠️":e.includes("🦁")?"🦁":e.includes("🪑")?"🪑":e.includes("🚗")?"🚗":"📢"}function s(){if(!c)return;let e=r?i:i.slice(0,3);if(e.length===0){c.innerHTML='<div class="notification-empty">📭 لا توجد إشعارات</div>';return}let n="";for(const t of e){const o=t.unread?"unread":"";n+=`
                <div class="notification-item ${o}" data-id="${t.id}">
                    <div class="notification-icon">${I(t.title)}</div>
                    <div class="notification-content">
                        <div class="notification-title">${w(t.title)}</div>
                        <div class="notification-message">${w(t.message.substring(0,80))}${t.message.length>80?"...":""}</div>
                        <div class="notification-time">🕐 ${w(t.time)}</div>
                    </div>
                </div>
            `}if(c.innerHTML=n,!r&&i.length>3){const t=document.createElement("div");t.className="notification-show-all",t.innerHTML='<button class="show-all-btn">📋 عرض جميع الإشعارات</button>',c.appendChild(t),t.querySelector(".show-all-btn").addEventListener("click",o=>{o.stopPropagation(),r=!0,s()})}if(r&&i.length>3){const t=document.createElement("div");t.className="notification-show-less",t.innerHTML='<button class="show-less-btn">⬆️ عرض أقل</button>',c.appendChild(t),t.querySelector(".show-less-btn").addEventListener("click",o=>{o.stopPropagation(),r=!1,s()})}document.querySelectorAll(".notification-item").forEach(t=>{t.addEventListener("click",o=>{o.stopPropagation();const h=parseInt(t.dataset.id);if(!isNaN(h)){const y=i.find(D=>D.id===h);y&&y.unread&&(y.unread=!1,u(),s(),f(),v())}})})}function N(){let e=!1;for(const n of i)n.unread&&(n.unread=!1,e=!0);e&&(u(),s(),f(),v()),setTimeout(()=>B(),300)}function k(){if(a)if(d)a.classList.remove("active"),d=!1,r&&(r=!1,s());else{a.classList.add("active"),d=!0;let e=!1;for(const n of i)n.unread&&(n.unread=!1,e=!0);e&&(u(),s(),f(),v())}}function B(){a&&d&&(a.classList.remove("active"),d=!1)}function T(){return g=document.getElementById("notificationBell"),l=document.getElementById("notificationBadge"),a=document.getElementById("notificationDropdown"),c=document.getElementById("notificationsList"),p=document.getElementById("markAllReadBtn"),g?(g.addEventListener("click",e=>{e.stopPropagation(),k()}),p&&p.addEventListener("click",e=>{e.stopPropagation(),N()}),document.addEventListener("click",e=>{d&&a&&!a.contains(e.target)&&e.target!==g&&B()}),!0):(console.warn("⚠️ زر الإشعارات غير موجود في الصفحة"),!1)}window.addNotification=function(e,n,t){const o=i.length>0?Math.max(...i.map(h=>h.id))+1:1;return i.unshift({id:o,title:e,message:n,time:t||"الآن",unread:!0}),u(),s(),f(),v(),o},window.refreshNotifications=function(){S()};function L(){T()?(S(),console.log("✅ notifications.js تم التحميل بنجاح")):(console.warn("⚠️ notifications.js: العناصر غير جاهزة، إعادة المحاولة بعد 500ms"),setTimeout(L,500))}document.readyState==="loading"?document.addEventListener("DOMContentLoaded",L):L()})();
