console.log("🧩 sentenceReorder.js يتم تحميله...");class SentenceReorder{static overlay=null;static puzzleContainer=null;static parts=[];static shuffledParts=[];static slots=[];static currentQuestionId=null;static currentSentenceElement=null;static isOpen=!1;static isCorrect=!1;static iconElement=null;static currentText="";static isFirstTime=!0;static isAnimating=!1;static open(t,e,s,i){if(console.log("🧩 فتح SentenceReorder"),this.isOpen){console.log("⚠️ نافذة مفتوحة بالفعل");return}this.iconElement=i;const a=e.textContent||e.innerText||"";if(this.currentText=a.trim(),!this.currentText){console.warn("⚠️ لا يوجد نص للجملة");return}this.currentContainer=t,this.currentSentenceElement=e,this.currentQuestionId=s,this.isOpen=!0,this.isCorrect=!1,this.parts=this.splitSentence(this.currentText),this.shuffledParts=this.shuffleArray([...this.parts]),this.createOverlay(),this.showIntroCard()}static showIntroCard(){if(!this.puzzleContainer)return;this.puzzleContainer.innerHTML="";const t=document.createElement("h3");t.textContent="أعد تشكيل الجملة. ✨",t.style.cssText=`
            margin: 0 0 16px 0;
            color: #1e293b;
            font-size: 1.1rem;
            text-align: center;
            font-weight: 500;
        `,this.puzzleContainer.appendChild(t);const e=document.createElement("p");e.textContent="تساعدك هذه الميزة على تثبيت الجملة الصحيحة في الذاكرة. إذا وجدت جملة صعبة، فإن إعادة ترتيبها يجعل تذكّرها أسهل.",e.style.cssText=`
            margin: 0 0 20px 0;
            color: #64748b;
            font-size: 0.85rem;
            text-align: center;
            line-height: 1.6;
            max-width: 400px;
            margin-left: auto;
            margin-right: auto;
        `,this.puzzleContainer.appendChild(e);const s=document.createElement("button");s.textContent="أنا جاهز",s.style.cssText=`
            background: #2c3e66;
            color: white;
            border: none;
            border-radius: 8px;
            padding: 10px 28px;
            font-size: 0.9rem;
            font-weight: 500;
            cursor: pointer;
            transition: all 0.2s ease;
            display: block;
            margin: 0 auto;
            font-family: inherit;
        `,s.addEventListener("mouseenter",()=>{s.style.background="#1a2a4a"}),s.addEventListener("mouseleave",()=>{s.style.background="#2c3e66"}),s.addEventListener("click",()=>{console.log("🚀 المستخدم جاهز، بدء التدريب"),this.startTraining()}),this.puzzleContainer.appendChild(s),this.addCloseButton()}static startTraining(){this.isFirstTime=!1,this.renderPuzzle()}static splitSentence(t){let e=t.trim();if(e.length<20)return[e];const s=e.split(/\s+/),i=s.length;if(i<=4)return[s.join(" ")];const a=Math.ceil(i/3),o=[];for(let r=0;r<3;r++){const n=r*a,l=Math.min(n+a,i);if(n<i){const c=s.slice(n,l).join(" ");o.push(c)}}for(;o.length<3;)o.push("");return o}static shuffleArray(t){const e=[...t];for(let s=e.length-1;s>0;s--){const i=Math.floor(Math.random()*(s+1));[e[s],e[i]]=[e[i],e[s]]}return e}static createOverlay(){this.close(),this.overlay=document.createElement("div"),this.overlay.id="sentencePuzzleOverlay",this.overlay.style.cssText=`
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: rgba(0, 0, 0, 0.3);
            backdrop-filter: blur(3px);
            display: flex;
            align-items: center;
            justify-content: center;
            z-index: 99999;
            opacity: 0;
            transition: opacity 0.25s ease;
        `,this.puzzleContainer=document.createElement("div"),this.puzzleContainer.id="sentencePuzzleCard",this.puzzleContainer.style.cssText=`
            background: #ffffff;
            border-radius: 14px;
            padding: 24px 28px;
            max-width: 620px;
            width: 92%;
            box-shadow: 0 20px 50px rgba(0, 0, 0, 0.1);
            transform: scale(0.96) translateY(8px);
            transition: transform 0.3s cubic-bezier(0.2, 0.9, 0.4, 1.1);
            position: relative;
            max-height: 90vh;
            overflow-y: auto;
            border: 1px solid #e8edf4;
        `,this.overlay.appendChild(this.puzzleContainer),document.body.appendChild(this.overlay),requestAnimationFrame(()=>{this.overlay.style.opacity="1",this.puzzleContainer.style.transform="scale(1) translateY(0)"}),this.overlay.addEventListener("click",t=>{t.target===this.overlay&&this.close()}),document.addEventListener("keydown",this.handleEsc)}static renderPuzzle(){if(!this.puzzleContainer){console.error("❌ puzzleContainer غير موجود");return}this.puzzleContainer.innerHTML="";const t=document.createElement("h3");t.textContent="أعد تشكيل الجملة. ✨",t.style.cssText=`
            margin: 0 0 20px 0;
            color: #1e293b;
            font-size: 1.05rem;
            text-align: center;
            font-weight: 500;
        `,this.puzzleContainer.appendChild(t);const e=document.createElement("div");e.id="sentenceSlotsContainer",e.style.cssText=`
            display: flex;
            gap: 12px;
            justify-content: center;
            margin-bottom: 20px;
        `,this.slots=[];const s=this.parts.length;for(let o=0;o<s;o++){const r=document.createElement("div");r.className="sentence-slot",r.dataset.slotIndex=o,r.style.cssText=`
                flex: 1;
                min-width: 100px;
                min-height: 50px;
                padding: 10px 16px;
                border: 2px dashed #dce2ec;
                border-radius: 8px;
                background: #f8fafc;
                display: flex;
                align-items: center;
                justify-content: center;
                text-align: center;
                font-size: 0.85rem;
                color: transparent;
                transition: all 0.2s ease;
                cursor: pointer;
                font-weight: 400;
                box-sizing: border-box;
            `,r.textContent="",r.addEventListener("dragover",n=>{n.preventDefault(),r.dataset.hasPart||(r.style.borderColor="#94a3b8",r.style.background="#f1f5f9")}),r.addEventListener("dragleave",()=>{r.dataset.hasPart||(r.style.borderColor="#dce2ec",r.style.background="#f8fafc")}),r.addEventListener("drop",n=>{n.preventDefault();const l=parseInt(n.dataTransfer.getData("text/plain"));this.handleDrop(l,o)}),r.addEventListener("click",()=>{if(!(this.isCorrect||this.isAnimating)&&r.dataset.hasPart){const n=r.textContent,l=this.shuffledParts.indexOf(n);l!==-1&&(this.clearSlot(o),this.showCard(l))}}),this.slots.push(r),e.appendChild(r)}this.puzzleContainer.appendChild(e);const i=document.createElement("div");i.id="sentenceCardsContainer",i.style.cssText=`
            display: flex;
            gap: 12px;
            justify-content: center;
            margin-bottom: 20px;
            padding: 12px;
            background: #f8fafc;
            border-radius: 8px;
            border: 1px solid #e8edf4;
            min-height: 60px;
            flex-wrap: wrap;
        `,this.shuffledParts.forEach((o,r)=>{if(!o||o.trim()==="")return;const n=document.createElement("div");n.className="sentence-card",n.dataset.partIndex=r,n.dataset.partText=o,n.draggable=!0,n.style.cssText=`
                flex: 1;
                min-width: 120px;
                padding: 12px 18px;
                background: #ffffff;
                border: 1px solid #dce2ec;
                border-radius: 8px;
                cursor: grab;
                font-size: 0.85rem;
                color: #1e293b;
                transition: all 0.2s ease;
                box-shadow: 0 1px 3px rgba(0, 0, 0, 0.04);
                user-select: none;
                font-weight: 400;
                text-align: center;
                word-break: break-word;
                line-height: 1.5;
                box-sizing: border-box;
            `,n.textContent=o,n.addEventListener("dragstart",l=>{if(this.isCorrect||this.isAnimating){l.preventDefault();return}l.dataTransfer.setData("text/plain",r.toString()),n.style.opacity="0.5",n.style.transform="scale(0.98)"}),n.addEventListener("dragend",()=>{n.style.opacity="1",n.style.transform="scale(1)"}),n.addEventListener("click",()=>{if(this.isCorrect||this.isAnimating)return;const l=this.slots.findIndex(c=>!c.dataset.hasPart);l!==-1&&this.handleDrop(r,l)}),n.addEventListener("mouseenter",()=>{!this.isCorrect&&!this.isAnimating&&!n.dataset.placed&&(n.style.borderColor="#94a3b8",n.style.background="#f1f5f9")}),n.addEventListener("mouseleave",()=>{!this.isCorrect&&!this.isAnimating&&!n.dataset.placed&&(n.style.borderColor="#dce2ec",n.style.background="#ffffff")}),i.appendChild(n)}),this.puzzleContainer.appendChild(i);const a=document.createElement("button");a.id="sentenceCheckBtn",a.textContent="تحقق",a.style.cssText=`
            background: #2c3e66;
            color: white;
            border: none;
            border-radius: 8px;
            padding: 10px 28px;
            font-size: 0.9rem;
            font-weight: 500;
            cursor: pointer;
            transition: all 0.2s ease;
            width: 100%;
            font-family: inherit;
        `,a.addEventListener("mouseenter",()=>{a.style.background="#1a2a4a"}),a.addEventListener("mouseleave",()=>{a.style.background="#2c3e66"}),a.addEventListener("click",()=>{this.checkOrder()}),this.puzzleContainer.appendChild(a),this.addCloseButton()}static addCloseButton(){const t=document.createElement("button");t.textContent="✕",t.style.cssText=`
            position: absolute;
            top: 12px;
            right: 16px;
            background: none;
            border: none;
            font-size: 18px;
            color: #94a3b8;
            cursor: pointer;
            transition: all 0.2s ease;
            padding: 4px 8px;
            line-height: 1;
            font-family: inherit;
        `,t.addEventListener("mouseenter",()=>{t.style.color="#475569"}),t.addEventListener("mouseleave",()=>{t.style.color="#94a3b8"}),t.addEventListener("click",()=>{this.close()}),this.puzzleContainer.appendChild(t)}static handleDrop(t,e){if(this.isCorrect||this.isAnimating||t<0||t>=this.shuffledParts.length||e<0||e>=this.slots.length)return;const s=this.slots[e];if(s){if(s.dataset.hasPart){const i=s.textContent,a=this.shuffledParts.indexOf(i);this.clearSlot(e),this.placePartInSlot(t,e),a!==-1&&this.showCard(a)}else this.placePartInSlot(t,e);this.clearCorrectionColors()}}static placePartInSlot(t,e){const s=document.querySelector(`.sentence-card[data-part-index="${t}"]`),i=this.slots[e];if(!s||!i)return;const a=s.dataset.partText;s.style.display="none",s.dataset.placed="true",i.textContent=a,i.dataset.hasPart="true",i.dataset.partIndex=t,i.style.borderColor="#dce2ec",i.style.background="#ffffff",i.style.color="#1e293b",i.style.fontWeight="400"}static clearSlot(t){const e=this.slots[t];e&&(e.textContent="",delete e.dataset.hasPart,delete e.dataset.partIndex,e.style.borderColor="#dce2ec",e.style.background="#f8fafc",e.style.color="transparent",e.style.fontWeight="400")}static showCard(t){const e=document.querySelector(`.sentence-card[data-part-index="${t}"]`);e&&(e.style.display="block",delete e.dataset.placed)}static checkOrder(){if(this.isCorrect||this.isAnimating||this.slots.filter(s=>s.dataset.hasPart).length<this.parts.length)return;let e=!0;this.slots.forEach((s,i)=>{const a=s.textContent,o=this.parts[i];s.style.borderColor="#dce2ec",s.style.background="#ffffff",a===o?(s.style.borderColor="#28a745",s.style.background="#d4edda",s.style.color="#155724"):(e=!1,s.style.borderColor="#e67e22",s.style.background="#fef0e0",s.style.color="#856404")}),e&&this.onSuccess()}static onSuccess(){this.isCorrect=!0,this.isAnimating=!0,this.slots.forEach(t=>{t.style.borderColor="#28a745",t.style.background="#d4edda",t.style.color="#155724"}),this.iconElement&&(this.iconElement.textContent="✅",this.iconElement.style.color="#28a745",this.iconElement.style.opacity="0.8",this.iconElement.classList.add("success")),setTimeout(()=>{this.close(),this.isAnimating=!1},1e3)}static clearCorrectionColors(){this.slots.forEach(t=>{t.dataset.hasPart?(t.style.borderColor="#dce2ec",t.style.background="#ffffff",t.style.color="#1e293b"):(t.style.borderColor="#dce2ec",t.style.background="#f8fafc",t.style.color="transparent")})}static close(){this.iconElement&&!this.isCorrect&&(this.iconElement.textContent="🔀",this.iconElement.style.color="#64748b",this.iconElement.style.opacity="0.6",this.iconElement.classList.remove("success")),this.overlay&&(this.overlay.style.opacity="0",this.puzzleContainer&&(this.puzzleContainer.style.transform="scale(0.96) translateY(8px)"),setTimeout(()=>{this.overlay&&this.overlay.parentNode&&this.overlay.remove(),this.overlay=null,this.puzzleContainer=null,this.isOpen=!1,this.isCorrect=!1,this.isAnimating=!1},250)),document.removeEventListener("keydown",this.handleEsc)}static handleEsc(t){t.key==="Escape"&&SentenceReorder.isOpen&&SentenceReorder.close()}static init(){console.log("🧩 SentenceReorder: جاهز للعمل")}}window.SentenceReorder=SentenceReorder,document.readyState==="loading"?document.addEventListener("DOMContentLoaded",()=>{SentenceReorder.init()}):SentenceReorder.init(),console.log("✅ sentenceReorder.js تم تحميله");
